### ISSUE TITLE
Location card will not load inside Telegram "browser" on iPhone

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/cognicity-reports-telegram-server#1]
Hi @talltom @matthewberryman ! We are in the office and tried to report through telegram by sending messages to @BencanaBot, so cool! There were some issues about the location card:

- I got the link from the Bot and once I opened the card, it shows "Pick Location" but the maps could not loaded inside the Telegram browser, but it works with Safari, and directly shows my current location and the pin can be moved. FYI I am using iPhone 5.

- @fadmastuti used Android phone, did not experience the same issue, she could open it inside directly. However she did not turn on their location at all but it detects her location as here, which is about 1 km away from our office:
![2017 01 10 17 06](https://cloud.githubusercontent.com/assets/22338984/21802507/9ce196a0-d758-11e6-9622-6941183e5ea7.PNG)

cc: @anexact 

Thank you!

**Comment by tomasholderness** [comment]
Notes:
- confirmed bug using iPhone 5.
- should probably move this over to [petabencana.id](https://github.com/urbanriskmap/petabencana.id/issues) as it is a web issue
- need to understand what powers the "telegram browser".

**Comment by tomasholderness** [comment]
Thanks for the information @prittandrani. Just to confirm, this is a bug only with iPhone?

**Comment by prittandrani** [comment]
@talltom, yes, I tried with another Android phone and it loaded, but not with another iPhone 6.

**Comment by tomasholderness** [comment]
Hi @prittandrani we've pushed some updates to the cards recently, I wonder when you get chance if you can test this again.

cc. @MaanasaPriyaa @abrahamq as they are working on Telegram support for Chennai

**Comment by fadmastuti** [comment]
Hi @talltom ,
I did some tests of the (telegram) cards recently using android. When I just hit the link, this error message appeared:

![1](https://cloud.githubusercontent.com/assets/2441950/21897974/d23748ec-d91d-11e6-80d7-fa37706f46fd.jpeg)

When I did retry the same think, the cards looked just fine. However, I didn't turn my geolocation on. I wonder if it tracked me from my latest location (p.s I am at Depok while it plot me at central Jakarta). But I think it should've warn me to turn on my geolocation before it plots me to the certain location (?)

I also tried to continue reporting with geolocation off. And this error message appeared:
![2](https://cloud.githubusercontent.com/assets/2441950/21898194/94e56a9a-d91e-11e6-8599-e6ae86ef744f.jpeg)

cc @prittandrani

**Comment by tomasholderness** [comment]
Hi Dika,

It looks like the server thinks you already submitted that card (perhaps
part of a previous error).

If you ask the bot for a new card do you still get the same error?

Thanks.

**Comment by fadmastuti** [comment]
Hi,

Yes. I still get the error message. I refresh the page and try to turn on my geolocation as well but it still appears.

**Comment by tomasholderness** [comment]
Can you try with this link? https://dev.petabencana.id/cards/Bk8zMVHLe

**Comment by tomasholderness** [comment]
I haven't been able to recreate the issue yet. I just succesfuly submitted a report from Depok. https://dev.petabencana.id/map/jakarta/478641

**Comment by fadmastuti** [comment]
success! all good now.
I tried to re-type /flood on telegram so I get the updated link I guess and try to make a report again.
My bad.. sorry for that :)

**Comment by tomasholderness** [comment]
No problem. I'm not sure what happened to your previous report - but the key thing is that you can only submit a report once. After that you have to ask the bot for a new card link. We can keep an eye on this and let me know if you experience the same issue again.

**Comment by fadmastuti** [comment]
will let you know definitely. 

btw, should I open a new issue regarding the location?
in my opinion - although the map is successfully loaded, not all of the people know where are they on the map if we are not automatically show them their current location. what do you think?

**Comment by tomasholderness** [comment]
Hi @fadmastuti yes if you could open a new issue that would be great. Thanks

**Comment by prittandrani** [comment]
@talltom sorry for the late reply, I tried it but still wont work in
Telegram and I cant choose "next" button now (last time I can do it without
the map loaded) but works well in Safari browser.

From telegram


From Safari

**Comment by matthewberryman** [comment]
Fixed (and also for in-app browsing on Twitter clients on iOS, and Firefox desktop) thanks to some great work by @ojha-url
